version: '3.8'

services:
  telegram-bot-api:
    image: aiogram/telegram-bot-api:latest
    environment:
      TELEGRAM_API_ID: "<api-id>"
      TELEGRAM_API_HASH: "<api-hash>"
      TELEGRAM_LOCAL: true
    volumes:
      - telegram-bot-api-data:/var/lib/telegram-bot-api
    ports:
      - "8081:8081"

  nginx:
    build: nginx/.
    volumes:
      - telegram-bot-api-data:/var/lib/telegram-bot-api
    ports:
      - "80:80"

volumes:
  telegram-bot-api-data: